version: "3.3"

services:
  web:
    build: .
    volumes:
      - ./infra/letsencrypt:/etc/letsencrypt
    ports:
      - "80:80"
      - "443:443"
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.1
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - discovery.type=single-node